version: 2
updates:

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "area/chore"
      - "area/dockerfile"

  # Keep the workflows' actions current too
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
