version: '2'

services:
  local-dns-linux:
    build: .
    image: christhomas/supervisord-dnsmasq:latest
    restart: always
    network_mode: bridge

  local-dns-osx:
    build: .
    image: christhomas/supervisord-dnsmasq:latest
    restart: always
    network_mode: bridge
    ports:
      - 53:53/udp
