name: Docker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches:
      - main
    tags:
      - '*.*.*'
    paths-ignore:
      - 'test/*'
      - '.gitignore'
      - 'docker-compose.yml'
      - 'LICENSE'
      - '*.md'

jobs:
  multiarch-build-alpine:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Docker tags for Alpine based image
        id: docker_meta_alpine
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: |
            ghcr.io/antimatter-studios/docker-dns
          tags: |
            type=semver,suffix=-alpine,pattern={{version}}
            type=semver,suffix=-alpine,pattern={{major}}.{{minor}}
            type=raw,value=alpine,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
          flavor: latest=false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the Alpine based image
        id: docker_build_alpine
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8
          push: true
          tags: ${{ steps.docker_meta_alpine.outputs.tags }}
          labels: ${{ steps.docker_meta_alpine.outputs.labels }}

      - name: Images digests
        run: echo ${{ steps.docker_build_alpine.outputs.digest }}
